/**
 * Golden fixture tests for @omega/deadline-engine.
 *
 * The fixture is generated by `test/generate-golden.ts` using a naïve
 * independent reference implementation. These tests simply pin the engine to
 * the reference — any divergence is a real behavior change that must be
 * reviewed and the fixture regenerated.
 */

import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, test } from 'vitest';

import { computeDeadline, computeProgress, extend } from '../src/index';
import type { PlazoType, PqrSnapshot, TenantConfig } from '../src/types';
import { DeadlineEngineError } from '../src/types';

const HERE = dirname(fileURLToPath(import.meta.url));

const FIXTURE_PATH = resolve(HERE, 'fixtures/golden.json');

interface DeadlineCase {
  id: string;
  label?: string;
  input: {
    issuedAt: string;
    plazoType: PlazoType;
    tenantConfig?: TenantConfig;
  };
  expected: {
    deadlineAt: string;
    unit: string;
    amount: number;
    holidaysSkipped?: string[];
  };
}

interface ExtensionCase {
  id: string;
  label?: string;
  input: {
    pqr: {
      issuedAt: string;
      plazoType: PlazoType;
      deadlineAt: string;
      tenantConfig?: TenantConfig;
    };
    reason: string;
    newDeadlineAt: string;
  };
  expected:
    | { shouldThrow: false; newDeadlineAt: string }
    | { shouldThrow: true; errorCode: string };
}

interface ProgressCase {
  id: string;
  label?: string;
  input: {
    pqr: {
      issuedAt: string;
      plazoType: PlazoType;
      deadlineAt: string;
      tenantConfig?: TenantConfig;
    };
    now: string;
  };
  expected: {
    status: string;
    unit: string;
    amount: number;
  };
}

interface Fixture {
  generatedAt: string;
  deadlineCases: DeadlineCase[];
  extensionCases: ExtensionCase[];
  progressCases: ProgressCase[];
}

const fixture = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8')) as Fixture;

function toPqr(c: ExtensionCase['input']['pqr'] | ProgressCase['input']['pqr']): PqrSnapshot {
  if (c.tenantConfig) {
    return {
      issuedAt: c.issuedAt,
      plazoType: c.plazoType,
      deadlineAt: c.deadlineAt,
      tenantConfig: c.tenantConfig,
    };
  }
  return {
    issuedAt: c.issuedAt,
    plazoType: c.plazoType,
    deadlineAt: c.deadlineAt,
  };
}

// ---------------------------------------------------------------------------
// Spot-check — the demo case. If this ever regresses, the demo is broken.
// ---------------------------------------------------------------------------
describe('spot-check (demo moment)', () => {
  test('2026-04-18 saturday peticion_general matches engine', () => {
    const c = fixture.deadlineCases.find(
      (x) => x.id === 'spot-check-2026-04-18' || x.label === 'spot-check-2026-04-18',
    );
    expect(c, 'spot-check case must exist in fixture').toBeDefined();
    const result = computeDeadline(
      c!.input.issuedAt,
      c!.input.plazoType,
      c!.input.tenantConfig,
    );
    expect(result.deadlineAt.toISOString()).toBe(c!.expected.deadlineAt);
  });
});

// ---------------------------------------------------------------------------
// Deadline cases — every entry in `deadlineCases`.
// ---------------------------------------------------------------------------
describe('golden deadline cases', () => {
  for (const c of fixture.deadlineCases) {
    test(`${c.id}: ${c.label ?? ''}`, () => {
      const result = computeDeadline(c.input.issuedAt, c.input.plazoType, c.input.tenantConfig);
      expect(result.deadlineAt.toISOString()).toBe(c.expected.deadlineAt);
      expect(result.unit).toBe(c.expected.unit);
      expect(result.amount).toBe(c.expected.amount);
      if (c.expected.holidaysSkipped) {
        expect([...result.holidaysSkipped].sort()).toEqual(
          [...c.expected.holidaysSkipped].sort(),
        );
      }
    });
  }
});

// ---------------------------------------------------------------------------
// Extension cases — cover valid extensions + cap / ordering rejections.
// ---------------------------------------------------------------------------
describe('golden extension cases', () => {
  for (const c of fixture.extensionCases) {
    test(`${c.id}: ${c.label ?? ''}`, () => {
      const pqr = toPqr(c.input.pqr);

      if (c.expected.shouldThrow) {
        try {
          extend(pqr, c.input.reason, c.input.newDeadlineAt);
          throw new Error(`expected extend() to throw ${c.expected.errorCode}`);
        } catch (err) {
          expect(err).toBeInstanceOf(DeadlineEngineError);
          expect((err as DeadlineEngineError).code).toBe(c.expected.errorCode);
        }
      } else {
        const result = extend(pqr, c.input.reason, c.input.newDeadlineAt);
        expect(result.newDeadlineAt.toISOString()).toBe(c.expected.newDeadlineAt);
        expect(result.auditEvent.type).toBe('deadline_extended');
        expect(result.auditEvent.reason).toBe(c.input.reason);
        expect(result.auditEvent.newDeadline.toISOString()).toBe(
          c.expected.newDeadlineAt,
        );
      }
    });
  }
});

// ---------------------------------------------------------------------------
// Progress cases — status + basic shape.
// ---------------------------------------------------------------------------
describe('golden progress cases', () => {
  for (const c of fixture.progressCases) {
    test(`${c.id}: ${c.label ?? ''}`, () => {
      const pqr = toPqr(c.input.pqr);
      const now = new Date(c.input.now);
      const result = computeProgress(pqr, now);
      expect(result.status).toBe(c.expected.status);
      expect(result.unit).toBe(c.expected.unit);
      expect(result.total).toBe(c.expected.amount);
      expect(result.elapsed).toBeGreaterThanOrEqual(0);
      expect(result.percentUsed).toBeGreaterThanOrEqual(0);
    });
  }
});
