/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalSeguimientoRouteImport } from './routes/portal.seguimiento'
import { Route as PortalRadicarRouteImport } from './routes/portal.radicar'
import { Route as PortalAyudaRouteImport } from './routes/portal.ayuda'
import { Route as PortalSeguimientoRadicadoRouteImport } from './routes/portal.seguimiento.$radicado'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSeguimientoRoute = PortalSeguimientoRouteImport.update({
  id: '/seguimiento',
  path: '/seguimiento',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRadicarRoute = PortalRadicarRouteImport.update({
  id: '/radicar',
  path: '/radicar',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAyudaRoute = PortalAyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSeguimientoRadicadoRoute =
  PortalSeguimientoRadicadoRouteImport.update({
    id: '/$radicado',
    path: '/$radicado',
    getParentRoute: () => PortalSeguimientoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/ayuda': typeof PortalAyudaRoute
  '/portal/radicar': typeof PortalRadicarRoute
  '/portal/seguimiento': typeof PortalSeguimientoRouteWithChildren
  '/portal/': typeof PortalIndexRoute
  '/portal/seguimiento/$radicado': typeof PortalSeguimientoRadicadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal/ayuda': typeof PortalAyudaRoute
  '/portal/radicar': typeof PortalRadicarRoute
  '/portal/seguimiento': typeof PortalSeguimientoRouteWithChildren
  '/portal': typeof PortalIndexRoute
  '/portal/seguimiento/$radicado': typeof PortalSeguimientoRadicadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/ayuda': typeof PortalAyudaRoute
  '/portal/radicar': typeof PortalRadicarRoute
  '/portal/seguimiento': typeof PortalSeguimientoRouteWithChildren
  '/portal/': typeof PortalIndexRoute
  '/portal/seguimiento/$radicado': typeof PortalSeguimientoRadicadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/portal/ayuda'
    | '/portal/radicar'
    | '/portal/seguimiento'
    | '/portal/'
    | '/portal/seguimiento/$radicado'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal/ayuda'
    | '/portal/radicar'
    | '/portal/seguimiento'
    | '/portal'
    | '/portal/seguimiento/$radicado'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/portal/ayuda'
    | '/portal/radicar'
    | '/portal/seguimiento'
    | '/portal/'
    | '/portal/seguimiento/$radicado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/seguimiento': {
      id: '/portal/seguimiento'
      path: '/seguimiento'
      fullPath: '/portal/seguimiento'
      preLoaderRoute: typeof PortalSeguimientoRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/radicar': {
      id: '/portal/radicar'
      path: '/radicar'
      fullPath: '/portal/radicar'
      preLoaderRoute: typeof PortalRadicarRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/ayuda': {
      id: '/portal/ayuda'
      path: '/ayuda'
      fullPath: '/portal/ayuda'
      preLoaderRoute: typeof PortalAyudaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/seguimiento/$radicado': {
      id: '/portal/seguimiento/$radicado'
      path: '/$radicado'
      fullPath: '/portal/seguimiento/$radicado'
      preLoaderRoute: typeof PortalSeguimientoRadicadoRouteImport
      parentRoute: typeof PortalSeguimientoRoute
    }
  }
}

interface PortalSeguimientoRouteChildren {
  PortalSeguimientoRadicadoRoute: typeof PortalSeguimientoRadicadoRoute
}

const PortalSeguimientoRouteChildren: PortalSeguimientoRouteChildren = {
  PortalSeguimientoRadicadoRoute: PortalSeguimientoRadicadoRoute,
}

const PortalSeguimientoRouteWithChildren =
  PortalSeguimientoRoute._addFileChildren(PortalSeguimientoRouteChildren)

interface PortalRouteChildren {
  PortalAyudaRoute: typeof PortalAyudaRoute
  PortalRadicarRoute: typeof PortalRadicarRoute
  PortalSeguimientoRoute: typeof PortalSeguimientoRouteWithChildren
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAyudaRoute: PortalAyudaRoute,
  PortalRadicarRoute: PortalRadicarRoute,
  PortalSeguimientoRoute: PortalSeguimientoRouteWithChildren,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
